name: mltle
channels:
  - conda-forge
dependencies:
  - python=3.7.13
  - pip:
    - tensorflow
    - tensorflow_addons
    - scikit-plot
    - lifelines
    - scikit-learn
    - rdkit-pypi
    - tqdm